Entity/Post.php
<?php

namespace Ghazy\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ghazy\BlogBundle\Utils\Blog as Blog;
use Eko\FeedBundle\Item\ItemInterface;
/**
 * Post
 */
class Post implements ItemInterface
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $body;

    /**
     * @var string
     */
    private $token;

    /**
     * @var boolean
     */
    private $is_activated;

    /**
     * @var \DateTime
     */
    private $created_at;

    /**
     * @var \DateTime
     */
    private $updated_at;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return Post
     */
    public function setBody($body)
    {
        $this->body = $body;
    
        return $this;
    }

    /**
     * Get body
     *
     * @return string 
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set token
     *
     * @param string $token
     * @return Post
     */
    public function setToken($token)
    {
        $this->token = $token;
    
        return $this;
    }

    /**
     * Get token
     *
     * @return string 
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Set is_activated
     *
     * @param boolean $isActivated
     * @return Post
     */
    public function setIsActivated($isActivated)
    {
        $this->is_activated = $isActivated;
    
        return $this;
    }

    /**
     * Get is_activated
     *
     * @return boolean 
     */
    public function getIsActivated()
    {
        return $this->is_activated;
    }

    /**
     * Set created_at
     *
     * @param \DateTime $createdAt
     * @return Post
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    
        return $this;
    }

    /**
     * Get created_at
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param \DateTime $updatedAt
     * @return Post
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    
        return $this;
    }

    /**
     * Get updated_at
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
	    if(!$this->getCreatedAt())
		  {
		    $this->created_at = new \DateTime();
		  }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
         $this->updated_at = new \DateTime();
    }
    public function getTitleSlug()
    {
    	return Blog::slugify($this->getTitle());
    }
    public function getBodyTruncuted()
    {
    	$limit = Blog::limit;
    	return Blog::truncate($this->getBody(), $limit);
    }
	public function setTokenValue()
    {
    	if(!$this->getToken())
    	{
    		$this->token = sha1($this->getTitle().rand(11111, 99999));
    	}
    }
    public function __toString()
    {
	return $this->getTitle();
     }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $comments;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add comments
     *
     * @param \Ghazy\BlogBundle\Entity\Comment $comments
     * @return Post
     */
    public function addComment(\Ghazy\BlogBundle\Entity\Comment $comments)
    {
        $this->comments[] = $comments;
    
        return $this;
    }

    /**
     * Remove comments
     *
     * @param \Ghazy\BlogBundle\Entity\Comment $comments
     */
    public function removeComment(\Ghazy\BlogBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComments()
    {
        return $this->comments;
    }
    public function getFeedItemTitle() {
	return $this->getTitle();
   }
   public function getFeedItemDescription() {
   	$string ='tags: ';
   	foreach ($this->getTags() as $tag)
   	{
   		$string.= ' '.$tag.',';
   	}
	return substr($string, 0, -1);
   }
   public function getFeedItemPubDate() {
	return $this->getCreatedAt();
   }
   public function getFeedItemLink()
   {
	return 'http://www.ghazybenahmed.com/article/'.$this->getTitleSlug().'/'.$this->getId() ;
   }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $tags;


    /**
     * Add tags
     *
     * @param \Ghazy\BlogBundle\Entity\Tag $tags
     * @return Post
     */
    public function addTag(\Ghazy\BlogBundle\Entity\Tag $tags)
    {
    	$tags->addPost($this);
        $this->tags[] = $tags;
    
        return $this;
    }

    /**
     * Remove tags
     *
     * @param \Ghazy\BlogBundle\Entity\Tag $tags
     */
    public function removeTag(\Ghazy\BlogBundle\Entity\Tag $tags)
    {
        $this->tags->removeElement($tags);
    }

    /**
     * Get tags
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTags()
    {
        return $this->tags;
    }
}

Controller/DefaultController.php
<?php

namespace Ghazy\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    public function indexAction()
    {

        return $this->render('GhazyBlogBundle:Default:index.html.twig');
    }
    public function aboutmeAction()
    {
    	return $this->render('GhazyBlogBundle:Default:aboutme.html.twig');
    }
    public function tutorialsAction()
    {
    	$em = $this->getDoctrine()->getEntityManager();
    	$tutos = $em->createQuery('SELECT j FROM GhazyBlogBundle:Post j WHERE j.is_activated = :param')->setParameter('param',true)->getResult();
    	return $this->render('GhazyBlogBundle:Default:tutorials.html.twig', array('tutos'=>$tutos));
    }
    public function tutorialAction($slug, $id)
    {
    	$em = $this->getDoctrine()->getEntityManager();
    	$tuto = $em->getRepository('GhazyBlogBundle:Post')->find($id);
		$comments = $em->createQuery('SELECT j FROM GhazyBlogBundle:Comment j WHERE j.is_activated = :param AND j.post =:post')->setParameters(array('param'=>true, 'post' => $tuto->getId()))->getResult();
    	return $this->render('GhazyBlogBundle:Default:tutorial.html.twig', array('tuto'=>$tuto, 'comments'=>$comments));
    }
    public function feedAction()
    {
		$em = $this->getDoctrine()->getEntityManager();
        $articles = $em->createQuery('SELECT j FROM GhazyBlogBundle:Post j WHERE j.is_activated = :param')->setParameter('param',true)->getResult();

        $feed = $this->get('eko_feed.feed.manager')->get('article');
        $feed->addFromArray($articles);

        return new Response($feed->render('rss'));
    }
    public function tagAction($tagSlug)
    {
    	$em = $this->getDoctrine()->getEntityManager();
    	$tag = $em->getRepository('GhazyBlogBundle:Tag')->findOneBySlug($tagSlug);
    	if (!$tag) {
    		throw $this->createNotFoundException('Unable to find Job entity.');
    	}
    	$tutos = $em->createQuery('SELECT j FROM GhazyBlogBundle:Post j WHERE j.is_activated = :param AND :tagparam MEMBER OF j.tags')->setParameters(array('param'=>true, 'tagparam'=>$tag->getId()))->getResult();
    	return $this->render('GhazyBlogBundle:Default:tutorials.html.twig', array('tutos'=>$tutos));
    	
    }
    
}

Resources/views/Default/aboutme.html.twig
{% extends 'GhazyBlogBundle::layout.html.twig' %}
{% block title %}Ghazy Ben Ahmed - About Me{% endblock %}
{% block content %}
   <!--start holder-->
	<script language="javascript">
			$(document).ready(
				function (){
					$("#home").removeClass('current');
					$("#tuto").removeClass('current');
					$("#aboutme").addClass('current');
					$("#projects").removeClass('current');
				});
		</script>
   <div class="holder_content">
    <h2>Professional</h2>
    <br>
	<p>I&#8217;m Web Developer working primarily in PHP Symfony. I&#8217;m currently Confirmed Web Developer for a Tunis based Internet company with responsibility for PHP/MySQL backend and frontend development.</p>
	<p>I like also haking python and javascript.</p>
	<br>
	<h2>Personal</h2>
	<br>
	<p>I&#8217;m 26 years old. Currently living in Tunis, I&#8217;m single, and I &#8217;m trying to enjoy my life looking for new experienes.</p>
	<br>
	<h2>Contact</h2>
	<br>
	<p>You can reach me via email at contact_at_ghazybenahmed.com</p>
	<p>You can find my CV on <a href="http://www.doyoubuzz.com/ghazy-abdelhamid-ben-ahmed" target="_blank">doyoubuzz</a>, or you can simply download it <a href="{{ asset('uploads/cv/ghazy_ben_ahmed.pdf') }}">here</a>.</p>
    <br>
    </div>
    <!--end holder-->
{% endblock %}

Resources/views/Default/index.html.twig
{% extends 'GhazyBlogBundle::layout.html.twig' %}
{% block content %}
   <!--start holder-->

   <div class="holder_content">
   
   <section class="group1">
   <h3>About Me</h3>
   	<p>My name is Ghazy Ben Ahmed, I&#8217;m 26, I live in <a href="https://maps.google.com/maps?q=tunis&#038;hl=fr&#038;ie=UTF8&#038;ll=36.809285,10.17334&#038;spn=12.425359,25.356445&#038;sll=46.55886,2.834473&#038;sspn=10.681986,25.356445&#038;t=h&#038;hnear=Tunis,+M%C3%A9dina+de+Tunis,+Gouvernorat+de+Tunis,+Tunisie&#038;z=6" title="Tunis, Tunisia" target="_blank"><span>Tunis</span></a>.<br />
I&#8217;m mostly a Web developer, but as you may suppose, I&#8217;m not a Web designer.</p>
    <a href="{{ path('ghazy_blog_aboutme') }}"><span class="read_more">Read more...</span></a>

	</section>
	

     
   <section class="group2">
   <h3>Articles</h3>
   	<p>In this corner of my site, I share tutorials and help you to get your own work done.It is all open source.It is all hosted at <a href="https://github.com/bghazy">github</a>.</p>
	<a href="{{ path('ghazy_blog_tutorials') }}"><span class="read_more">Read more ...</span></a>

	</section>


       
   <section class="group3">
   <h3>Portfolio</h3>
   	<p>During my career, I have participate in developing many projects, here I&#8217;m going to list some of them.</p>
	<a href="#"><span class="read_more">Read more...</span></a>

	</section>

  
   </div>
   <!--end holder-->
   
   <!--start holder-->

   <div class="holder_content1">
    <section class="group4">
   <h3>Services</h3>
   	<p>If your next project is in Symfony, Django or Node.js,you can write me an email, I will be glad to do it for you.</p>
    <div class="pikachoose">
	<ul id="pikame" >
		<li><a href="#"><img src="{{ asset('bundles/ghazyblog/img/symfony.jpg')}}" width="500" height="250"  alt="picture"/></a><span>“Symfony: The PHP framework  of Sensio Labs.”</span></li>
		<li><a href="#"><img src="{{ asset('bundles/ghazyblog/img/django-python.png')}}" width="500" height="250" alt="picture"/></a><span>“Django: The Phyton framework. “ </span></li>
		<li><a href="#"><img src="{{ asset('bundles/ghazyblog/img/nodejs.png')}}" width="500" height="250" alt="picture"/></a><span>“Node.js: Enjoy runing javascript on server side. ”</span></li>
	   </ul>
       </div>

	</section>


       
   <section class="group5">
   	<p><span class="purple">1)</span><strong>Symfony</strong> is an Open Source PHP Web applications development framework. It was originally conceived by the Sensio Labs agency for the development of web sites for its own customers. Symfony was published in 2005 and today it is among the leading frameworks available for PHP development. </p>
      	<p><span class="purple">2)</span><strong>Django</strong> is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.It is really the framework for perfectionists with deadlines as it called in its offical web site. Django is developed in 2005 and it is now the best Python framework.</p>
   	<p><span class="purple">3)</span><strong>Node.js</strong> is a server side software system designed for writing scalable Internet applications, notably web servers. Programs are written on the server side in JavaScript, using event-driven, asynchronous I/O to minimize overhead and maximize scalability.</p>


	</section>

   
    </div>
    <!--end holder-->
{% endblock %}

Resources/views/Default/portfolio.html.twig
{% extends 'GhazyBlogBundle::layout.html.twig' %}
{% block content %}
   <!--start holder-->
	<script language="javascript">
			$(document).ready(
				function (){
					$("#home").removeClass('current');
					$("#tuto").removeClass('current');
					$("#aboutme").removeClass('current');
					$("#projects").addClass('current');
				});
		</script>
   <div class="holder_content minheight">
   
    </div>
    <!--end holder-->
{% endblock %}

Resources/views/Default/tutorial.html.twig
{% extends 'GhazyBlogBundle::layout.html.twig' %}
{% block title %}Ghazy Ben Ahmed - {{ tuto.title }} {% endblock %}
{% block content %}
   <!--start holder-->
	<script language="javascript">
			$(document).ready(
				function (){
					$("#home").removeClass('current');
					$("#tuto").removeClass('current');
					$("#aboutme").removeClass('current');
					$("#projects").removeClass('current');
				});
		</script>
<div class="holder_content minheight">
<article><div class="date"><time datetime="{{ tuto.createdAt|date('c') }}">{{ tuto.createdAt|date('l, F j, Y') }}</time></div>
<h3>{{ tuto.title }}</h3>
<ul class="tags">
<li>tags:</li>
{% for tag in tuto.tags %}
<li class="tag"><a href="{{ path('ghazy_blog_tag', {'tagSlug': tag.slug}) }}" rel="tag">{{ tag.title }}</a></li>
{% endfor %}
</ul>
    <div>{{ tuto.body|raw }}</div>
</article>
<section class="comments" id="comments">
        <section class="previous-comments">
            <h3>Comments</h3>
            {% include 'GhazyBlogBundle:Comment:index.html.twig' with { 'comments': comments } %}
        </section>
        {% for key, flash in app.session.getFlashes() %}
    	<div class="notices">
	 <span id="notification-text">{{ flash }}</span>
	</div>
	{% endfor %}
        <h3>Add Comment</h3>
        {% render 'GhazyBlogBundle:Comment:new' with { 'blog_id': tuto.id } %}
    </section>
</div>
    <!--end holder-->
{% endblock %}

Resources/views/Default/tutorials.html.twig
{% extends 'GhazyBlogBundle::layout.html.twig' %}
{% block title %}Ghazy Ben Ahmed - Articles{% endblock %}
{% block content %}
   <!--start holder-->
	<script language="javascript">
			$(document).ready(
				function (){
					$("#home").removeClass('current');
					$("#tuto").addClass('current');
					$("#aboutme").removeClass('current');
					$("#projects").removeClass('current');
				});
		</script>
   <div class="holder_content minheight">
    {% for tuto in tutos %}
    <div>
    <div class="date"><time datetime="{{ tuto.createdAt|date('c') }}">{{ tuto.createdAt|date('l, F j, Y') }}</time></div>
<span><a href="{{ path('ghazy_blog_tutorial', { 'id': tuto.id, 'slug': tuto.titleSlug }) }}">{{ tuto.title }}</a></span>
<ul class="tags">
{% for tag in tuto.tags %}
<li class="tag"><a href="{{ path('ghazy_blog_tag', {'tagSlug': tag.slug}) }}" rel="tag">{{ tag.title }}</a></li>
{% endfor %}
</ul>    
<div>{{ tuto.bodyTruncuted|raw }}</div>
    </div>
{% else %}
    <p>There are no articles yet. Comming soon...</p>
    {% endfor %}
    </div>
    <!--end holder-->
{% endblock %}